### ISSUE TITLE
[suggestion] currently airing, not aired yet 

### ISSUE THREAD

**Issue by ZeroOmar** [Mordonus/MALClient#9] opened 2016-04-21 09:13 UTC
it would be great to see the "currently airing" and "not aired yet" text in the anime list next to the picture in list view

**Comment by Mordonus** [comment] 2016-04-21 11:46
How about this?

![image](https://cloud.githubusercontent.com/assets/6102530/14707846/2090ac28-07c7-11e6-9bfd-ed1d4ed0cd6e.png)

If anime is airing then the day of airing will be white if it's not yet aired but its air day is known it will be greyed out. If anime is in any other state there won't be anything visible?

(Screenshot from desktop version but it's essentially the same thing)

**Comment by ZeroOmar** [comment] 2016-04-21 13:53
thank you very much
maybe in the "not aired yet" state if the date is "unknown" it could show "???" in that area ;)

**Comment by Mordonus** [comment] 2016-04-21 14:51
The problem is that state does not come with standard list data and it's a bit problematic to implement , so I'll pass on that for the time being.

Update with this feature should be available tomorrow.

Desktop version will be released either tomorrow or next weekend (Mon-Tue) , depending on how my testing succeeds.

**Closed by Mordonus** 2016-04-21 14:51 UTC

**Comment by ZeroOmar** [comment] 2016-04-21 15:06
no problem
and thank you again for this great app
